runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: crmadmin/assets/

- url: /libs
  static_dir: crmadmin/libs/

- url: /uploads
  static_dir: crmadmin/uploads/
  
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: crmadmin/assets/.*\.(gif|png|jpg)$

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: crmadmin/uploads/.*\.(gif|png|jpg|pdf|doc|docx|xls|xlsx)$
  
- url: /.*
  script: crmadmin/index.php